"""Added ElementsToProcess table

Revision ID: 8263df5f84a4
Revises: 
Create Date: 2023-12-17 14:06:32.473892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8263df5f84a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elementstoprocess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_bulk', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ElementsToProcess_idBulk_IDX', 'elementstoprocess', ['id_bulk', 'status'], unique=False)
    op.create_index('ElementsToProcess_status_IDX', 'elementstoprocess', ['status'], unique=False)
    op.create_index(op.f('ix_elementstoprocess_id'), 'elementstoprocess', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_elementstoprocess_id'), table_name='elementstoprocess')
    op.drop_index('ElementsToProcess_status_IDX', table_name='elementstoprocess')
    op.drop_index('ElementsToProcess_idBulk_IDX', table_name='elementstoprocess')
    op.drop_table('elementstoprocess')
    # ### end Alembic commands ###
